# Site settings
title: Alexey A.
header-img: img/home-bg.jpg
email: alexey.alkhutov@dunice.ru
copyright_name: Dunice
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://yourdomain.com"
github_username:  dunice-alkhutov
vk_username: n1xan
email_username:  alexey.alkhutov@dunice.ru

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
